[package]
name = "subgraph"
version = "0.2.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2021"
description = "Write Subgraphs for The Graph protocol in Rust 🦀"
license = "BSD-2-Clause"

[dependencies]
indexmap = "1"
